default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: servisne_info_development

test:
  <<: *default
  database: servisne_info_test

production:
  <<: *default
  database: servisne_info_production
  username: servisne
  password: <%= ENV['SERVISNE_INFO_DATABASE_PASSWORD'] %>
